name = "BasicRL"
uuid = "e0db2b0d-bd4a-435e-8889-3b7f783a93ac"
authors = ["Huy-Quang-Dao <daoquanghuy2203@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"